- name: Déploiement PROD
  hosts: prod
  become: yes
  tasks:

    - name: Installer les dépendances
      apt:
        name:
          - git
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Installer Flask
      pip:
        name: flask

    - name: Cloner le dépôt depuis GitHub
      git:
        repo: 'https://github.com/Denhetsu/Project_TP.git'
        dest: /opt/app
        force: yes

    - name: Créer un service systemd pour l'app Flask
      copy:
        dest: /etc/systemd/system/app.service
        content: |
          [Unit]
          Description=Flask App
          After=network.target

          [Service]
          ExecStart=/usr/bin/python3 /opt/app/app.py
          WorkingDirectory=/opt/app
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Activer et démarrer le service Flask
      systemd:
        name: app
        enabled: yes
        state: restarted

    - name: Créer fichier de log de confirmation
      copy:
        content: "Déploiement PROD terminé le {{ ansible_date_time.date }} à {{ ansible_date_time.time }}"
        dest: /opt/app/deploy.log
