---
- name: Ensure /opt/app exists
  file:
    path: /opt/app
    state: directory

- name: Deploy latest code
  git:
    repo: "https://github.com/Denhetsu/Project_TP.git"
    dest: /opt/app
    version: "{{ git_branch | default('dev') }}"
    force: yes

- name: Make run.sh executable
  file:
    path: /opt/app/app/run.sh
    mode: '0755'

- name: Run the application
  shell: ./run.sh
  args:
    chdir: /opt/app/app

- name: Create confirmation file
  copy:
    content: "Deployed on {{ ansible_date_time.date }}\n"
    dest: /opt/app/DEPLOYMENT_OK.txt

- name: Générer la page pour Nginx
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'

- name: Redémarrer Nginx pour prendre en compte la nouvelle page
  service:
    name: nginx
    state: restarted
