---
- name: Ensure /opt/app exists
  file:
    path: /opt/app
    state: directory

- name: Deploy latest code
  git:
    repo: "https://github.com/TON-UTILISATEUR/TON-REPO.git"
    dest: /opt/app
    version: "{{ git_branch | default('dev') }}"
    force: yes

- name: Make run.sh executable
  file:
    path: /opt/app/app/run.sh
    mode: '0755'

- name: Run the application
  shell: ./run.sh
  args:
    chdir: /opt/app/app

- name: Create confirmation file
  copy:
    content: "Deployed on {{ ansible_date_time.date }}\n"
    dest: /opt/app/DEPLOYMENT_OK.txt

- name: Générer une page de confirmation
  template:
    src: index.html.j2
    dest: /opt/app/index.html
